set encoding=utf-8
cmap w!! w !sudo tee > /dev/null %
syntax enable
colorscheme desert
set cc=80
set listchars=tab:▸\ ,eol:¬
set list
set background=dark
set encoding=utf8
set ffs=unix,dos,mac
set ai
set si
set relativenumber
set mouse=a
set hidden
set magic
set number
set ignorecase
set smartcase
set hlsearch
set incsearch
set history=1000
set undolevels=1000
set title
map <F4> :e %:p:s,.h$,.X123X,:s,.cpp$,.h,:s,.X123X$,.cpp,<CR>
filetype plugin on
